config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  resources :images

  root to: "trails#index"
  resources :comments
  resources :usertrails
  resources :trails do
    resources :comments
    resources :images
  end

  resources :users
  resources :gear, only: :index
  resources :best, only: :index
  resources :dashboard, only: :index

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider', to: 'sessions#create', as: 'twitter'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post 'search', to: 'trails#search'
  get 'search', to: 'trails#search'

  namespace :api do
    namespace :v1 do
      resources :trails
    end
  end

  mount Resque::Server.new, at: "/resque"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :verify_user

  def index
    @comments = current_user.comments.all
    @images = current_user.images.all
    source = current_user.trails.all
    @trails = source.map {|i| DashboardDecorator.new(i)}
  end

  private
  def verify_user
    redirect_to root_path unless current_user
  end
end

app/views/dashboard/index.html.erb
<div class="container">
    <h1 id='dashboard-title'><%= current_user.name %></h1>
     <% if @trails.empty? %>
       <div id="empty-spot">
         <h2>Like Some Trails!</h2>
       </div>
      <% else %>
        <% @trails.each do |trail| %>
          <div class="row" id="dashboard-info">
            <h3 id='dashboard-h3'>My Trails</h3>
              <div class='col-md-6'>
                <h3 id='dashboard-h3'><%= trail.name %></h3>
                <li><%= trail.image %></li>
                <li>Website: <%= link_to trail.url %></li>
                <li>City: <%= trail.city %></li>
                <li>State :<%= trail.state %></li>
                <li>Lattitude: <%= trail.lat %></li>
                <li>Longitude: <%= trail.lon %></li>
              </div>

              <div class='col-md-6'>
                <li>This trail is <%= trail.distance %> miles long.</li>
                <li>This trail has a rating of: <%= trail.rating %> on a scale of 1-5.</li>
                <li>Directions: <%= trail.directions %></li>
                <li><%= trail.short_description %></li>
              </div>

              <%= link_to trail.name, trail_path(trail), class: 'btn btn-info' %><br>
              <%= link_to 'Remove', usertrail_path(trail), confirm: "Are you sure you want to remove this trail?", method: :delete, class: 'btn btn-warning padding' %>
          </div>
        <% end %>
      <% end %>
      <div class="row">
        <div class="col-md-6" id="bubbles1">
          <h3 id='dashboard-h3'>My Comments</h3>
          <% @comments.each do |comment| %>
             <strong><%= comment.trail.name %></strong><br>
            You said: <%= comment.body %><br>
            Commented <%= time_ago_in_words(comment.created_at) %> ago.<br>
          <% end %>
        </div>
        <div class="col-md-6" id="bubbles2">
          <h3 id='dashboard-h3'>My Pics</h3>
          <% @images.each do |image| %>
            <%= image_tag image.image, class: 'search-image' %>
          <% end %>
        </div>
      </div>
  </div>