config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  resources :images

  root to: "trails#index"
  resources :comments
  resources :usertrails
  resources :trails do
    resources :comments
    resources :images
  end

  resources :users
  resources :gear, only: :index
  resources :best, only: :index
  resources :dashboard, only: :index

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider', to: 'sessions#create', as: 'twitter'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post 'search', to: 'trails#search'
  get 'search', to: 'trails#search'

  namespace :api do
    namespace :v1 do
      resources :trails
    end
  end

  mount Resque::Server.new, at: "/resque"
end

app/views/shared/_navbar.html.erb
<nav id="nav_bar" class="navbar navbar-inverse navbar-fixed-top sticky" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MountainMadness", root_path, class: "navbar-brand", id: "site_title" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <!-- <li><%#= link_to 'Forum', comments_path %></li> -->
        <!-- <li><%#= link_to 'Gear', gear_index_path %></li> -->
        <!-- <li><%#= link_to "Best Of", best_index_path, class: "welcome-link"%></li> -->
        <% if current_user %>
          <li><%= link_to "Dashboard", dashboard_index_path, class: "welcome-link"%></li>
        <% end %>

        <li><div id="login-fields">
          <% if current_user %>
            <li><%= link_to 'Logout', signout_path %></li>
          <% else %>
            <li><%= link_to 'Login with Twitter', twitter_path("twitter") %></li>
          <% end %>
        </div></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_search_bar.html.erb
<div id="sidebar">
  <div id="search_bar">
    <%= form_tag search_path, method: :get do %>
      <%= label_tag "Search by City" %>
      <%= text_field_tag :city, params[:city], :id => 'search_field' %><br>
      <%= label_tag "Search by State" %>
      <%= text_field_tag :state, params[:state], :id => 'search_field' %><br>
      <%= submit_tag "Search", :name => nil %>
      <%#= link_to_function "Clear", "$('search_field').clear()" %>
    <% end %>
  </div>
</div>

app/views/shared/_search_results.html.erb
<% unless @trails.nil? %>
  <ul>
    <% @trails.parsed_response["places"].each do |trail| %>
  <li><%= trail.name %></li>
    <% end %>
  </ul>
<% end %>