config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  resources :images

  root to: "trails#index"
  resources :comments
  resources :usertrails
  resources :trails do
    resources :comments
    resources :images
  end

  resources :users
  resources :gear, only: :index
  resources :best, only: :index
  resources :dashboard, only: :index

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider', to: 'sessions#create', as: 'twitter'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post 'search', to: 'trails#search'
  get 'search', to: 'trails#search'

  namespace :api do
    namespace :v1 do
      resources :trails
    end
  end

  mount Resque::Server.new, at: "/resque"
end

app/models/trail.rb
class Trail < ActiveRecord::Base
  include HTTParty
  require 'open-uri'
  has_many :usertrails
  has_many :users, through: :usertrails
  has_many :comments
  has_many :images

  def self.search(state, city)
    TrailSearch.search
    # @response = party(build_url(state, city))
    # objects
  end

  def self.search_state(state)
    @response = party(build_state_url(state))
    objects
  end

  def self.search_city(city)
    @response = party(build_city_url(city))
    objects
  end

  def self.search_id(id)
    @response = party(build_unique_id_url(id))
    objects
  end

  def self.objects
    create_objects.each do |trail_attributes|
      create(trail_attributes) unless find_by(unique_id: trail_attributes[:unique_id])
    end
  end

  def self.party(searches)
    HTTParty.get(searches)
  end

  def self.create_objects
    @response.parsed_response["places"].map do |trail|
      if trail['activities'].present? && mountain_bike_trail?(trail['activities'].first)
        {
          unique_id: trail['unique_id'],
          distance: trail['activities'].first['length'],
          description: trail['activities'].first['description'],
          name: trail['name'],
          city: trail['city'],
          state: trail['state'],
          lat: trail['lat'],
          lon: trail['lon'],
          directions: trail['directions'],
          rating: trail['activities'].first['rating'],
          url: trail['activities'].first['url'],
          thumbnail: trail['activities'].first['thumbnail']
        }
      end
    end.compact!
  end

  def self.mountain_bike_trail?(activity)
    activity['activity_type_id'] && activity['activity_type_id'] == 5
  end

  def self.url
    'https://outdoor-data-api.herokuapp.com/api.json'
  end

  def self.api_key
    ENV['TRAIL_API_KEY']
  end

  def self.state(searched_state='')
    searched = URI::encode searched_state
    "&q[state_cont]=#{searched}"
  end

  def self.city(searched_city='')
    searched = URI::encode searched_city
    "&q[city_cont]=#{searched}"
  end

  def self.unique_id(searched_id='')
    searched = URI::encode searched_id
    "&q[unique_id_eq]=#{searched}"
  end

  def self.base
    url + api_key
  end

  def self.build_url(searched_state, searched_city)
    built = base + city(searched_city) + state(searched_state)
    built.to_s
  end

  def self.build_city_url(searched_city)
    built = base + city(searched_city)
    built.to_s
  end

  def self.build_state_url(searched_state)
    built = base + state(searched_state)
    built.to_s
  end

  def self.build_unique_id_url(searched_id)
    built = base + unique_id(searched_id)
    built.to_s
  end
end

app/controllers/api/v1/trails_controller.rb
class Api::V1::TrailsController < Api::V1::BaseController
  force_ssl unless Rails.env.development?

  before_action :authenticate, except: [:index, :show]

  respond_to :json, :xml

  def index
    respond_with Trail.all
  end

  def show
    respond_with Trail.find(params[:id])
  end

  def create
    respond_with Trail.create(trail_params)
  end

  def destroy
    respond_with Trail.destroy(params[:id])
  end

  def update
    respond_with Trail.update(params[:id], article_params)
  end

  def trail_params
    params.require(:trail).permit(:unique_id,
                                  :distance,
                                  :description,
                                  :name,
                                  :city,
                                  :state,
                                  :lat,
                                  :lon,
                                  :directions,
                                  :rating,
                                  :url,
                                  :thumbnail
                                  )
  end

  def authenticate
    authenticate_or_request_with_http_basic("Where's Your work visa?") do |nickname, oauth_secret|
      user = User.find_by(nickname: nickname)

      return true if user && user.oauth_secret == oauth_secret

      head :unauthorized
    end
  end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  respond_to :js
  def index
  end

  def show
    source   = Trail.find(params[:id])
    @trail   = TrailDecorator.new(source)
    @comment = Comment.new
    @image   = Image.new
  end

  def search
    if params[:state].length > 0 && params[:city].length > 0
      Trail.search(params[:state], params[:city])
      @trails = Trail.where(state: params[:state].capitalize, city: params[:city].capitalize)
    elsif params[:city].empty?
      Trail.search_state(params[:state])
      @trails = Trail.where(state: params[:state].capitalize)
    else
      Trail.search_city(params[:city])
      @trails = Trail.where(city: params[:city].capitalize)
    end
  end

  def edit
    trail = Trail.find(params[:id])
    current_user.trails << trail
  end

  def create
    @trail = current_user.trails.find_or_create_by(unique_id: trail_params[:unique_id])
    @trail.update_attributes(trail_params)

    if @trail.valid?
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def trail_params
    params.require(:trail).permit(:unique_id,
                                  :distance,
                                  :description,
                                  :name,
                                  :city,
                                  :state,
                                  :lat,
                                  :lon,
                                  :directions,
                                  :rating,
                                  :url,
                                  :thumbnail
                                  )
  end
end

app/views/trails/index.html.erb
<%= image_tag 'https://s3-us-west-2.amazonaws.com/aaronsprofessionalbucket/development/images/5/4b6a1aa9030e158888e079fba8f85519837f86d3-original.jpg', class: 'image' %>

<div id="home-comment">
  Here at Mountain Madness, we take your adrenaline addiction seriously. And we take your relaxing ride just as seriously. Lets ride this country together.

</div>

app/views/trails/search.html.erb
<%= image_tag 'https://s3-us-west-2.amazonaws.com/aaronsprofessionalbucket/development/images/6/1e80bf55939007e00ffdb1b16c42a42e398666c2-original.jpg', class: 'image' %>

<div class="container-fluid">
  <div class="row">
    <% unless @trails.nil? || @trails.empty? %>
      <ul>
        <% @trails.each do |trail| %>
          <div class='col-md-4' id='trail-info'>
            <h2 id='search-trail-name'><li><%= trail[:name] %></li></h2>
              <% image = trail[:thumbnail] %>
              <% if image.nil? %>
                <li><%= image_tag 'https://s3-us-west-2.amazonaws.com/aaronsprofessionalbucket/development/images/6/a2505a44d2f9784cc05bebbbd91c092049afe06e-medium.jpg', class: 'search-image' %></li>
              <% else image << ('jpg') unless image.ends_with?('jpg') %>
                <li><%= image_tag image.to_s, class: 'search-image' %></li>
              <% end %>
            <li>City:<%= trail[:city] %></li>
            <li>State:<%= trail[:state] %></li>
            <li>Directions:<%= truncate(trail[:directions], length: 55) %></li>
            <li>Lattitude:<%= trail[:lat] %></li>
            <li>Longitude:<%= trail[:lon] %></li>
            <li><%= truncate(trail[:description], length: 55) %></li>
            <li><%= link_to trail[:url] %></li>
            <li>This trail has a rating of: <%= trail[:rating] %> on a scale of 1-5.</li>
            <li>This trail is <%= trail[:distance] %> miles long.</li>
            <% unless current_user.nil? %>
              <%= link_to "LIKE", edit_trail_path(trail), remote: true, class: 'btn btn-default' %>
              <% end %>
            <%= link_to "More Info", trail_path(trail), class: 'btn btn-default' %>
          </div>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/trails/show.html.erb
<div class='container'>
  <h1 id='trail-title'><%= @trail.name %></h1>
  <div class='row'>
    <div class='col-md-6'>
      <div>
        <div class="row">
          <div id='show-trail'>
            <div id="trail-header">
              <li><h3>General Info</h3></li>
              <% if current_user.nil? %>
                <%= link_to "Login to LIKE a Trail", edit_trail_path(@trail), remote: true, class: 'btn btn-primary disabled', id: 'like' %>
              <% else %>
                <%= link_to "LIKE", edit_trail_path(@trail), remote: true, class: 'btn btn-primary', id: 'like' %>
              <% end %>
            </div>
              <div class='col-md-6'>
                <li><%= image_tag @trail.thumbnail, class: 'search-image' %></li>
                <li><%= link_to @trail.url %></li>
                <li><%= @trail.city %></li>
                <li><%= @trail.state %></li>
                <li><%= @trail.lat %></li>
                <li><%= @trail.lon %></li>
                <li>This trail has a rating of <%= @trail.rating %> out of 5</li>
                <li>This trail is <%= @trail.distance %> miles long</li>
              </div>
              <div class='second col-md-6'>
                <h3>Directions to Trail</h3>
                <li><%= @trail.directions %></li>
                <h3>Description of Trail</h3>
                <li><%= @trail.description %></li>
              </div>
          </div>
        </div>
      </div>
    </div>
    <div id="col-md-6">
      <div id="maps">
        <iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyC3SSrpIv1R-CUWu1zipfmYQIpfV9XlFQw&q=loc:<%="#{@trail.lat},#{@trail.lon}"%>" width="550px" height="500px"></iframe>
      </div>
    </div>
    <div class='col-md-6'>
      <h3>Community Photos</h3>
      <div id="images">
        <div id="new-image">
          <%= form_for [@trail, @image] do |f| %>
            <%= f.label :caption %>
            <%= f.text_field :name %>
            <%= f.file_field :image %>
            <% if current_user.nil? %>
              <%= f.submit "Login to Add an Image", :id => 'save', class: "btn btn-success disabled" %>
            <% else %>
              <%= f.submit "Add Image", :id => 'save', class: "btn btn-success" %>
            <% end %>
          <% end %>
        </div>
        <div class='row'>
            <% @trail.images.each do |image| %>
              <div class='col-md-6'>
                <%= image_tag image.image.url, class: 'trail-image' %><br>
                <p id='image-words'>
                  <%= image.name %>
                </p>
                <strong id='image-words'><%= image.user.name %></strong>
              </div>
            <% end %>
        </div>
      </div>
    </div>
    <div class='col-md-6'>
        <h3>Community Comments</h3>
      <div id="comments">
        <div id="new-comment">
          <%= form_for [@trail, @comment] do |f| %>
            <%= f.text_field :body %>
            <% if current_user.nil? %>
              <%= f.submit "Login to Add a Comment", :id => 'save', class: "btn btn-success disabled" %>
            <% else %>
              <%= f.submit "Add Comment", :id => 'save', class: "btn btn-success" %>
            <% end %>
          <% end %>
        </div>
        <div class='row'>
            <% @trail.comments.each do |comment| %>
              <div class='col-md-12'>
                <div id="each-comment">
                  <%= image_tag comment.user.image %>
                  <%= comment.body %>
                  <%= comment.user.name %>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>