config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  resources :images

  root to: "trails#index"
  resources :comments
  resources :usertrails
  resources :trails do
    resources :comments
    resources :images
  end

  resources :users
  resources :gear, only: :index
  resources :best, only: :index
  resources :dashboard, only: :index

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider', to: 'sessions#create', as: 'twitter'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post 'search', to: 'trails#search'
  get 'search', to: 'trails#search'

  namespace :api do
    namespace :v1 do
      resources :trails
    end
  end

  mount Resque::Server.new, at: "/resque"
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :image, Paperclip::Attachment.default_options.dup
  belongs_to :user
  belongs_to :trail
  validates_attachment_presence :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  respond_to :html, :json

  def new
    @image = Image.new
  end

  def index
    @images = Image.all
    respond_with @images
  end

  def create
    @trail = Trail.find(params[:trail_id])
    @image = current_user.images.new(image_params.merge(trail_id: @trail.id))
    if @image.save
      redirect_to :back
    else
      flash :now,  :error => "Image was not added. Please try again."
      render :back
    end
  end

  private
  def image_params
    params.require(:image).permit(:name, :image)
  end
end

app/views/images/new.html.erb
<div id="form-new">

<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h1 class="page-header">Upload Photo</h1>
        <%= bootstrap_form_for @image, url: images_path, html: {multipart: true} do |f| %>

          <%= f.text_field :name %>
          <%= f.file_field :image %>

          <%= f.submit "Save", :id => 'save', class: "btn btn-success" %>
          <%= link_to "Dashboard", dashboard_index_path, class: "btn btn-default" %>
        <% end %>
      </div>
  </div>
</div>
</div>